import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from './_components/providers';

const inter =
  // process.env.NODE_ENV === 'production'
  //   ? Inter({
  //       subsets: ['latin'],
  //       preload: true,
  //       variable: '--font-inter',
  //       display: 'swap',
  //     })
  // 	:
  {};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body data-card-size="default" className={`group ${inter.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
