import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '~/styles/globals/index.css';
import Providers from './_components/providers';
import type { PropsWithChildren } from 'react';

const inter = Inter({
  subsets: ['latin'],
  preload: true,
  variable: '--font-inter',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body data-card-size="default" className={`group ${inter.className}`}>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
