/** @import { Payment } from './types.ts' */

/** @type {Payment[]} */
export const paymentsData = [
  {
    id: "pay_001",
    amount: 420.69,
    status: "pending",
    email: "funny.bunny@haha.com",
    details: {
      lol: "ROFLcopter",
      bruh: "Toothbrush",
      xd: "Extra Delicious",
    },
    createdAt: "1981-01-03T22:00:00.000Z",
  },
  {
    id: "pay_002",
    amount: 123.45,
    status: "processing",
    email: "giggly.goose@lol.com",
    details: {
      lol: "LOLwut",
      bruh: "Paintbrush",
      xd: "Xtreme Dance",
    },
    createdAt: "2001-04-07T22:00:00.000Z",
  },
  {
    id: "pay_003",
    amount: 678.9,
    status: "success",
    email: "hilarious.hen@joke.com",
    details: {
      lol: "LMAO",
      bruh: "Hairbrush",
      xd: "X-ray Delight",
    },
    createdAt: "1980-02-07T22:00:00.000Z",
  },
  {
    id: "pay_004",
    amount: 987.65,
    status: "failed",
    email: "comedy.cat@meow.com",
    details: {
      lol: "ROFL",
      bruh: "Makeup Brush",
      xd: "Xtreme Donuts",
    },
    createdAt: "2011-10-09T22:00:00.000Z",
  },
  {
    id: "pay_005",
    amount: 555.55,
    status: "pending",
    email: "chuckle.chicken@cluck.com",
    details: {
      lol: "BWAHAHA",
      bruh: "Scrub Brush",
      xd: "Xylophone Dreams",
    },
    createdAt: "1990-08-03T21:00:00.000Z",
  },
  {
    id: "pay_006",
    amount: 404.04,
    status: "processing",
    email: "goofy.goat@baa.com",
    details: {
      lol: "Heehee",
      bruh: "BBQ Brush",
      xd: "Xylophone Dance",
    },
    createdAt: "2019-10-06T22:00:00.000Z",
  },
  {
    id: "pay_007",
    amount: 888.88,
    status: "success",
    email: "laughing.lion@roar.com",
    details: {
      lol: "Snicker",
      bruh: "Dish Brush",
      xd: "Xcellent Day",
    },
    createdAt: "1993-04-29T22:00:00.000Z",
  },
  {
    id: "pay_008",
    amount: 333.33,
    status: "failed",
    email: "jester.jack@fun.com",
    details: {
      lol: "Chortle",
      bruh: "Bottle Brush",
      xd: "Xylophone Dancer",
    },
    createdAt: "2017-05-30T22:00:00.000Z",
  },
  {
    id: "pay_009",
    amount: 999.99,
    status: "pending",
    email: "prankster.pig@oink.com",
    details: {
      lol: "Teehee",
      bruh: "Broom",
      xd: "Xtra Delight",
    },
    createdAt: "1993-08-30T21:00:00.000Z",
  },
  {
    id: "pay_010",
    amount: 101.01,
    status: "processing",
    email: "witty.wolf@howl.com",
    details: {
      lol: "Giggle",
      bruh: "Nail Brush",
      xd: "Xylophone Dreams",
    },
    createdAt: "1974-03-04T22:00:00.000Z",
  },
  {
    id: "pay_011",
    amount: 202.02,
    status: "success",
    email: "comical.cow@moo.com",
    details: {
      lol: "Snort",
      bruh: "Art Brush",
      xd: "Xylophone Drummer",
    },
    createdAt: "1990-07-06T21:00:00.000Z",
  },
  {
    id: "pay_012",
    amount: 303.03,
    status: "failed",
    email: "jovial.jellyfish@ocean.com",
    details: {
      lol: "Belly Laugh",
      bruh: "Hairbrush",
      xd: "Xylophone Expert",
    },
    createdAt: "1975-10-08T22:00:00.000Z",
  },
  {
    id: "pay_013",
    amount: 404.04,
    status: "pending",
    email: "laughing.lizard@reptile.com",
    details: {
      lol: "Chuckles",
      bruh: "Makeup Brush",
      xd: "Xylophone Extraordinaire",
    },
    createdAt: "2018-06-09T22:00:00.000Z",
  },
  {
    id: "pay_014",
    amount: 505.05,
    status: "processing",
    email: "giggles.gorilla@jungle.com",
    details: {
      lol: "Guffaw",
      bruh: "Scrub Brush",
      xd: "Xylophone Exuberance",
    },
    createdAt: "2017-11-02T22:00:00.000Z",
  },
  {
    id: "pay_015",
    amount: 606.06,
    status: "success",
    email: "snicker.snail@slowpoke.com",
    details: {
      lol: "Snicker",
      bruh: "Paintbrush",
      xd: "Xylophone Enthusiast",
    },
    createdAt: "1973-10-04T22:00:00.000Z",
  },
  {
    id: "pay_016",
    amount: 707.07,
    status: "failed",
    email: "cackle.crab@beach.com",
    details: {
      lol: "Chuckle",
      bruh: "Toothbrush",
      xd: "Xylophone Excitement",
    },
    createdAt: "2008-02-02T22:00:00.000Z",
  },
  {
    id: "pay_017",
    amount: 808.08,
    status: "pending",
    email: "giggle.goose@feathers.com",
    details: {
      lol: "Belly Laugh",
      bruh: "Dish Brush",
      xd: "Xylophone Ecstasy",
    },
    createdAt: "1986-03-31T22:00:00.000Z",
  },
  {
    id: "pay_018",
    amount: 909.09,
    status: "processing",
    email: "snort.squirrel@forest.com",
    details: {
      lol: "Giggle",
      bruh: "BBQ Brush",
      xd: "Xylophone Extravaganza",
    },
    createdAt: "2008-03-07T22:00:00.000Z",
  },
  {
    id: "pay_019",
    amount: 111.11,
    status: "success",
    email: "hilarious.hippo@river.com",
    details: {
      lol: "ROFL",
      bruh: "Bottle Brush",
      xd: "Xylophone Exhilaration",
    },
    createdAt: "2012-08-04T22:00:00.000Z",
  },
  {
    id: "pay_020",
    amount: 222.22,
    status: "failed",
    email: "silly.seal@ocean.com",
    details: {
      lol: "LMAO",
      bruh: "Nail Brush",
      xd: "Xylophone Excess",
    },
    createdAt: "2022-03-09T22:00:00.000Z",
  },
  {
    id: "pay_021",
    amount: 333.33,
    status: "pending",
    email: "whimsical.walrus@antarctica.com",
    details: {
      lol: "Heehee",
      bruh: "Art Brush",
      xd: "Xylophone Explosions",
    },
    createdAt: "1991-04-06T22:00:00.000Z",
  },
  {
    id: "pay_022",
    amount: 444.44,
    status: "processing",
    email: "chortling.chinchilla@funny.com",
    details: {
      lol: "Teehee",
      bruh: "Hairbrush",
      xd: "Xylophone Expeditions",
    },
    createdAt: "1982-07-03T22:00:00.000Z",
  },
  {
    id: "pay_023",
    amount: 555.55,
    status: "success",
    email: "hysterical.hamster@pet.com",
    details: {
      lol: "Snort",
      bruh: "Makeup Brush",
      xd: "Xylophone Excellence",
    },
    createdAt: "1974-10-06T22:00:00.000Z",
  },
  {
    id: "pay_024",
    amount: 666.66,
    status: "failed",
    email: "guffawing.giraffe@savannah.com",
    details: {
      lol: "Belly Laugh",
      bruh: "Scrub Brush",
      xd: "Xylophone Excelsior",
    },
    createdAt: "1992-09-06T21:00:00.000Z",
  },
  {
    id: "pay_025",
    amount: 777.77,
    status: "pending",
    email: "prank.penguin@iceberg.com",
    details: {
      lol: "Chuckles",
      bruh: "Paintbrush",
      xd: "Xylophone Exhibition",
    },
    createdAt: "1982-06-09T22:00:00.000Z",
  },
  {
    id: "pay_026",
    amount: 888.88,
    status: "processing",
    email: "jocular.jaguar@jungle.com",
    details: {
      lol: "Giggle",
      bruh: "Toothbrush",
      xd: "Xylophone Express",
    },
    createdAt: "1999-07-08T21:00:00.000Z",
  },
  {
    id: "pay_027",
    amount: 999.99,
    status: "success",
    email: "laughing.lemur@madagascar.com",
    details: {
      lol: "Guffaw",
      bruh: "Dish Brush",
      xd: "Xylophone Euphoria",
    },
    createdAt: "1985-03-04T22:00:00.000Z",
  },
  {
    id: "pay_028",
    amount: 1010.1,
    status: "failed",
    email: "snickering.snake@desert.com",
    details: {
      lol: "Snicker",
      bruh: "BBQ Brush",
      xd: "Xylophone Eclectic",
    },
    createdAt: "2012-05-07T22:00:00.000Z",
  },
  {
    id: "pay_029",
    amount: 1111.11,
    status: "pending",
    email: "laughing.lamb@farm.com",
    details: {
      lol: "ROFL",
      bruh: "Bottle Brush",
      xd: "Xylophone Embrace",
    },
    createdAt: "2015-09-07T22:00:00.000Z",
  },
  {
    id: "pay_030",
    amount: 1212.12,
    status: "processing",
    email: "giggling.goat@hill.com",
    details: {
      lol: "LMAO",
      bruh: "Nail Brush",
      xd: "Xylophone Enchantment",
    },
    createdAt: "2009-02-04T22:00:00.000Z",
  },
  {
    id: "pay_031",
    amount: 1313.13,
    status: "success",
    email: "chuckling.cheetah@savannah.com",
    details: {
      lol: "Heehee",
      bruh: "Art Brush",
      xd: "Xylophone Emission",
    },
    createdAt: "1976-06-06T21:00:00.000Z",
  },
  {
    id: "pay_032",
    amount: 1414.14,
    status: "failed",
    email: "laughing.lobster@sea.com",
    details: {
      lol: "Teehee",
      bruh: "Hairbrush",
      xd: "Xylophone Essence",
    },
    createdAt: "2001-08-31T21:00:00.000Z",
  },
  {
    id: "pay_033",
    amount: 1515.15,
    status: "pending",
    email: "giggles.goose@feathers.com",
    details: {
      lol: "Snort",
      bruh: "Makeup Brush",
      xd: "Xylophone Essence",
    },
    createdAt: "2002-10-08T22:00:00.000Z",
  },
  {
    id: "pay_034",
    amount: 1616.16,
    status: "processing",
    email: "snickering.snail@slowpoke.com",
    details: {
      lol: "Belly Laugh",
      bruh: "Scrub Brush",
      xd: "Xylophone Emulation",
    },
    createdAt: "1996-06-04T21:00:00.000Z",
  },
  {
    id: "pay_035",
    amount: 1717.17,
    status: "success",
    email: "cackling.crab@beach.com",
    details: {
      lol: "Chuckles",
      bruh: "Paintbrush",
      xd: "Xylophone Elevation",
    },
    createdAt: "1983-07-02T22:00:00.000Z",
  },
  {
    id: "pay_036",
    amount: 1818.18,
    status: "failed",
    email: "snorting.squirrel@forest.com",
    details: {
      lol: "Giggle",
      bruh: "Toothbrush",
      xd: "Xylophone Epiphany",
    },
    createdAt: "1980-09-08T21:00:00.000Z",
  },
  {
    id: "pay_037",
    amount: 1919.19,
    status: "pending",
    email: "hilarious.hippo@river.com",
    details: {
      lol: "Guffaw",
      bruh: "Dish Brush",
      xd: "Xylophone Expansion",
    },
    createdAt: "2001-09-06T21:00:00.000Z",
  },
  {
    id: "pay_038",
    amount: 2020.2,
    status: "processing",
    email: "silly.seal@ocean.com",
    details: {
      lol: "Snicker",
      bruh: "BBQ Brush",
      xd: "Xylophone Excellence",
    },
    createdAt: "1990-01-05T22:00:00.000Z",
  },
  {
    id: "pay_039",
    amount: 2121.21,
    status: "success",
    email: "whimsical.walrus@antarctica.com",
    details: {
      lol: "ROFL",
      bruh: "Bottle Brush",
      xd: "Xylophone Elation",
    },
    createdAt: "1980-08-02T21:00:00.000Z",
  },
  {
    id: "pay_040",
    amount: 2222.22,
    status: "failed",
    email: "chortling.chinchilla@funny.com",
    details: {
      lol: "LMAO",
      bruh: "Nail Brush",
      xd: "Xylophone Expertise",
    },
    createdAt: "2000-06-09T21:00:00.000Z",
  },
  {
    id: "pay_041",
    amount: 2323.23,
    status: "pending",
    email: "hysterical.hamster@pet.com",
    details: {
      lol: "Heehee",
      bruh: "Art Brush",
      xd: "Xylophone Exuberance",
    },
    createdAt: "2001-08-08T21:00:00.000Z",
  },
  {
    id: "pay_042",
    amount: 2424.24,
    status: "processing",
    email: "guffawing.giraffe@savannah.com",
    details: {
      lol: "Teehee",
      bruh: "Hairbrush",
      xd: "Xylophone Elixir",
    },
    createdAt: "1985-11-05T22:00:00.000Z",
  },
  {
    id: "pay_043",
    amount: 2525.25,
    status: "success",
    email: "prank.penguin@iceberg.com",
    details: {
      lol: "Snort",
      bruh: "Makeup Brush",
      xd: "Xylophone Embers",
    },
    createdAt: "1985-06-02T21:00:00.000Z",
  },
  {
    id: "pay_044",
    amount: 2626.26,
    status: "failed",
    email: "jocular.jaguar@jungle.com",
    details: {
      lol: "Belly Laugh",
      bruh: "Scrub Brush",
      xd: "Xylophone Envision",
    },
    createdAt: "1993-06-03T21:00:00.000Z",
  },
  {
    id: "pay_045",
    amount: 2727.27,
    status: "pending",
    email: "laughing.lemur@madagascar.com",
    details: {
      lol: "Chuckles",
      bruh: "Paintbrush",
      xd: "Xylophone Entity",
    },
    createdAt: "2009-04-30T21:00:00.000Z",
  },
  {
    id: "pay_046",
    amount: 2828.28,
    status: "processing",
    email: "snickering.snake@desert.com",
    details: {
      lol: "Giggle",
      bruh: "Toothbrush",
      xd: "Xylophone Energy",
    },
    createdAt: "1987-08-03T21:00:00.000Z",
  },
  {
    id: "pay_047",
    amount: 2929.29,
    status: "success",
    email: "laughing.lamb@farm.com",
    details: {
      lol: "Guffaw",
      bruh: "Dish Brush",
      xd: "Xylophone Echo",
    },
    createdAt: "2018-03-07T22:00:00.000Z",
  },
  {
    id: "pay_048",
    amount: 3030.3,
    status: "failed",
    email: "giggling.goat@hill.com",
    details: {
      lol: "Snicker",
      bruh: "BBQ Brush",
      xd: "Xylophone Embrace",
    },
    createdAt: "1997-06-09T21:00:00.000Z",
  },
  {
    id: "pay_049",
    amount: 3131.31,
    status: "pending",
    email: "chuckling.cheetah@savannah.com",
    details: {
      lol: "ROFL",
      bruh: "Bottle Brush",
      xd: "Xylophone Envision",
    },
    createdAt: "2013-10-04T22:00:00.000Z",
  },
  {
    id: "pay_050",
    amount: 3232.32,
    status: "processing",
    email: "laughing.lobster@sea.com",
    details: {
      lol: "LMAO",
      bruh: "Nail Brush",
      xd: "Xylophone Entity",
    },
    createdAt: "2004-08-06T21:00:00.000Z",
  },
];
